spring:
  application:
    name: wallet.management

  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_management?useSSL=false&allowPublicKeyRetrieval=true
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: in.pinnacle.apps.wallet.api.util.dto

server:
  port: 8081
